1904cs-papakagu/BountyHuntAR

- code-of-conduct.md
> UPDATE: wilson

- .gitignore
- App.js
Breaks out secrets into an ignored file, cleans up code and cuts down on comments
> refactored App.js

- js/Comps/UI/SigninScreen.js
- js/Comps/UI/WelcomeScreen.js
SigninScreen.js:
refactor: placed latitude and longitude in the same text tag and  resized latitude and longitude text in style sheet
WelcomeScreen.js
feat: Added user prompts to enter AR world or find a killzone
> feat: Added user prompts to enter AR world or find a killzone

- js/Comps/AR/ARScene.js
- js/Comps/AR/Bullet.js
- js/store/reducers/locations.js
-refactored and added bullet into own js file
> -added bullet into own file

- js/Comps/AR/ARScene.js
- js/Comps/AR/Bullet.js
-bullets no longer vanish after firing another bullet
> [feature] - bullets no longer vanish

- App.js
- js/Comps/AR/ARScene.js
- js/Comps/AR/Bullet.js
-gave bullet a timeout before being able to fire again
-changed bullet physics to have a constant velocity, instead of an acceleration
> [feature] - limited bullets and changed bullet physics

- js/Comps/UI/SigninScreen.js
Experimented with different component behaviors to make the signin screen avoid the keyboard when activated.
> feat: component will scroll up when keyboard is activated

- js/Comps/AR/ARScene.js
- js/store/reducers/locations.js
-user target set to null when target is eliminated
-increased velocity
> killzone updates on frontend

- App.js
- js/Comps/UI/KillZone.js
- js/store/index.js
- js/store/reducers/locations.js
-killzone ui shows current games and how far
-added thunk to grab all active games
> [FEAT]added front end for killzone

- App.js
- Game.js
- js/Comps/UI/KillZone.js
-can now start game in killzone 
-moved game component into own file
> [feat] updated KillZone to start game

- js/Comps/UI/KillZone.js
- js/store/reducers/game.js
- js/store/reducers/locations.js
> [BUGFIX] no more multiple active locations

- js/Comps/UI/KillZone.js
- js/Comps/UI/SigninScreen.js
- js/Comps/UI/WelcomeScreen.js
Added killzone banner and fixed background width color
removed coordinates in signin screen
> [STYLE] Added Active Killzone banner

- js/Comps/UI/KillZone.js
- js/Comps/UI/SigninScreen.js
- js/Comps/UI/WelcomeScreen.js
Added margin to buttons and changed button layout in killzone screen
> [style] Added margin to buttons

- App.js
- Game.js
- js/Comps/UI/WelcomeScreen.js
- js/store/index.js
- js/store/reducers/locations.js
- js/store/reducers/users.js
-can select crosshair on profile screen
-cleaned up some code
> [FEAT]added ability to select crosshair

- js/Comps/UI/WelcomeScreen.js
-selected crosshair now highlighted in red
> [feat] selected crosshair is now highlighted

- js/Comps/UI/EndScreen.js
Fixed Winner/Loser images on Android device. iOS devices render as expected.
> [BUGFIX] Fixed oversized image in winner/loser screen on Android devices

- js/Comps/UI/EndScreen.js
- js/Comps/UI/KillZone.js
- js/Comps/UI/SigninScreen.js
- js/Comps/UI/WelcomeScreen.js
Refactored colors to color code to keep code consistent
> [REFACTOR] Adjusted button style and refactored stylesheet color code

- js/Comps/AR/ARScene.js
- js/Comps/AR/Targets.js
> [FEAT] Implements basic wander and patrol animations for civilians and targets

- App.js
- js/Comps/UI/SigninScreen.js
- js/store/index.js
- js/store/reducers/users.js
-added sign up page
-using email to login and sign up is now case insensitive
> [feat]added sign up page

- App.js
- Game.js
- js/Comps/AR/ARScene.js
- js/store/index.js
- js/store/reducers/game.js
-user must reload after firing a certain amount of bullets
-user can now exit game, upon exit they are put back into profile page
> [FEAT] added reloading feature

- js/Comps/UI/WelcomeScreen.js
-crosshair selection now has side scroll
> [FEAT]added crosshair scroll

- Game.js
Successfully positioned transparent Reload button on ARScene
> [STYLE] Positioned transparent Reload button on ARScene

- App.js
- Game.js
- js/Comps/AR/ARScene.js
-can no longer shoot when reloading
> [FEAT] added additional features to reloading

- Game.js
- android/app/src/main/AndroidManifest.xml
- js/Comps/AR/ARScene.js
[FEAT] Added vibration feedback to button when shot is fired
[BUGFIX] SHOOT button ONLY vibrates while bullet can be fired.
[FEAT] Enabled vibration feedback to Andriod devices
> [FEAT] Added vibration feedback to button when shot is fired

- js/Comps/UI/KillZone.js
- js/Comps/UI/SigninScreen.js
[FEAT] Added scroll view for killzone list and changed button layout
Sign In / Sign Up buttons are next to instead of on top of each other
> [FEAT] Added scroll view for killzone list and changed button layout

- js/Comps/AR/ARScene.js
- js/store/index.js
- js/store/reducers/game.js
- js/store/reducers/users.js
-score now updates on profile screen
> [BUGFIX]fixed bug with score not updating
